Repository javorske/ProjektKontrolaBledow, pull requests merged in 2019-11, with the labels that each got.

#12 Fixes #3 Added option that counts letter in downloaded file and anoth…
  Analizator tekstu/Program.cs
  Analizator tekstu/bin/Debug/Analizator tekstu.exe
  Analizator tekstu/bin/Debug/Analizator tekstu.pdb
  Analizator tekstu/obj/Debug/Analizator tekstu.csprojAssemblyReference.cache
  Analizator tekstu/obj/Debug/Analizator tekstu.exe
  Analizator tekstu/obj/Debug/Analizator tekstu.pdb
Labels: enhancement

#14 Fixes #5 Added option which counts punctation marks
  Analizator tekstu/Program.cs
  Analizator tekstu/bin/Debug/Analizator tekstu.exe
  Analizator tekstu/bin/Debug/Analizator tekstu.pdb
  Analizator tekstu/obj/Debug/Analizator tekstu.csproj.CoreCompileInputs.cache
  Analizator tekstu/obj/Debug/Analizator tekstu.csproj.FileListAbsolute.txt
  Analizator tekstu/obj/Debug/Analizator tekstu.csprojAssemblyReference.cache
  Analizator tekstu/obj/Debug/Analizator tekstu.exe
  Analizator tekstu/obj/Debug/Analizator tekstu.pdb
  Analizator tekstu/obj/Debug/TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs
  Analizator tekstu/obj/Debug/TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.cs
  Analizator tekstu/obj/Debug/TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs
Labels: enhancement

#15 Fixes #6 Added option which counts sentences
  Analizator tekstu/Program.cs
Labels: enhancement

#16 added few fixes according to project documentation
  Analizator tekstu/Analizator tekstu.csproj
  Analizator tekstu/Program.cs
Labels: documentation

#17 Fixes #7 Added method that displays frequency of all letters of file,…
  Analizator tekstu/Program.cs
Labels: documentation, enhancement

#18 Fixes #8 Added an option that creates/overwrites the statistics.txt file
  Analizator tekstu/Program.cs
  Analizator tekstu/bin/Debug/Analizator tekstu.exe
  Analizator tekstu/bin/Debug/Analizator tekstu.pdb
  Analizator tekstu/bin/Debug/statystyki.txt
  Analizator tekstu/obj/Debug/Analizator tekstu.exe
  Analizator tekstu/obj/Debug/Analizator tekstu.pdb
Labels: documentation, enhancement
